<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Library</OutputType>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\ReVision.Core\ReVision.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="EmbedIO" Version="3.5.2" />
      <PackageReference Include="ILRepack.Lib.MSBuild.Task" Version="2.0.37">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="SixLabors.ImageSharp" Version="3.1.6" />
    </ItemGroup>

</Project>
